name: CI
permissions:
  contents: read

on: [pull_request]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        os: [ubuntu-latest]
        include:
          - python-version: 3.13  # Missing scipy wheels for 3.14 on Macos
            os: macos-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libegl1

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install ".[test]"

      - name: Test with pytest
        run: |
          pytest
